### ISSUE TITLE
Composer Optimizer

### ISSUE THREAD

**Issue by wandersonwhcr** [relesbao/php-service-skeleton#6]
Hello,

I have a suggestion: you can create a `Makefile` to install dependencies in development and optimize in production.

Example:

```make
COMPOSER_FLAGS = --prefer-dist

all: install

.PHONY: install
install:
	composer install ${COMPOSER_FLAGS}

.PHONY: optimize
optimize: COMPOSER_FLAGS = --no-dev --optimize-autoloader --classmap-authoritative
optimize: install
```

**Comment by wandersonwhcr** [comment]
You can create another recipe named `tests`:

```make
.PHONY: tests
tests: install
	php vendor/bin/phpunit
```

... and use with Travis CI at #5 .

**Comment by relesbao** [comment]
Nice suggestion, i will look forward to implement this when i solve #5 

Thanks!

**Comment by relesbao** [comment]
Added Makefile and made changes on composer.json to solve the issue.
