### ISSUE TITLE
Skeleton Namespace

### ISSUE THREAD

**Issue by wandersonwhcr** [relesbao/php-service-skeleton#7]
Is there a reason why your skeleton doesn't have a namespace in `composer.json`?

**Comment by wandersonwhcr** [comment]
Is because all namespaces must be found inside `src` directory?

Example:

```php
<?php

// filename: src/FooBar/Action/BazQux.php

namespace FooBar\Action;

class BazQux
{
    public function __invoke()
    {
        return __METHOD__;
    }
}
```

**Comment by relesbao** [comment]
Yes, i found that using PSR-0 pointing to `src`, developers are free to use whatever namespace they want following PSR-0 rules.

**Comment by wandersonwhcr** [comment]
ty!
